plugins:
  indexnow_enabled:
    default: true
    client: false
  indexnow_key:
    default: ""
    client: false
    hidden: true
  indexnow_endpoint:
    default: "https://api.indexnow.org/indexnow"
    client: false
    hidden: true
  indexnow_submit_on_create:
    default: true
    client: false
  indexnow_submit_on_update:
    default: true
    client: false
  indexnow_submit_on_reply:
    default: false
    client: false
  indexnow_excluded_category_ids:
    default: ""
    client: false
    type: list
  indexnow_excluded_tag_names:
    default: ""
    client: false
    type: list
  indexnow_hourly_limit:
    default: 0
    client: false
  indexnow_daily_limit:
    default: 10000
    client: false
